const Types = {
  GET_SERVER_CARTS: 'GET_SERVER_CARTS',
  GET_LOCAL_CARTS: 'GET_LOCAL_CARTS',
  ADD_SERVER_CART: 'ADD_SERVER_CART',
  ADD_LOCAL_CART: 'ADD_LOCAL_CART',
  CART_INC_COUNT: 'CART_INC_COUNT',
  CART_DES_COUNT: 'CART_DES_COUNT',
  CART_UPDATE_COUNT: 'CART_UPDATE_COUNT',
  CART_DEL_ITEM: 'CART_DEL_ITEM',
  SWITCH_PANEL: 'SWITCH_PANEL'
};

export {Types};